all: origin.txt principles-of-origin.txt sniff.txt

origin.txt: origin.xml
	../tools/xml2rfc-1.35pre1/xml2rfc.tcl origin.xml

principles-of-origin.txt: principles-of-origin.xml
	../tools/xml2rfc-1.35pre1/xml2rfc.tcl principles-of-origin.xml

sniff.txt: sniff.xml
	../tools/xml2rfc-1.35pre1/xml2rfc.tcl sniff.xml
